### ISSUE TITLE
Upgrade database

### ISSUE THREAD

**Issue by Matteo-** [alefranklin/BlueHorizon#9]
- Foto articoli
- Descrizione viaggio
- Aggiungere campi a users (admin, guest(?), customer)

**Comment by paguz42** [comment]
MORE INFO PLS

**Comment by Matteo-** [comment]
nel database ci devo essere tutte le informazioni necessarie a generare la pagina relativa ai viaggi in automativo, quindi tutti tutte le foto, le info, il pianeta...qualsiasi cosa vada messa nella paina di presentazione dettagliata el viagio
